---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  latex: ./tasks/latex.yml
  toml: ./tasks/toml.yml
  yaml: ./tasks/yaml.yml
  python: ./tasks/python.yml
  docker:
    taskfile: ./tasks/container.yml
    vars:
      RUNTIME: docker
  podman:
    taskfile: ./tasks/container.yml
    vars:
      RUNTIME: podman

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list
    silent: true

  clean:
    desc: Clean the project
    deps:
      - latex:clean
    cmds: []
    silent: true

  build:
    desc: Build the project
    deps:
      - latex:build
    cmds: []
    silent: true

  run:
    desc: Run the project
    deps:
      - python:run
    cmds: []
    silent: true

  seed:
    desc: Seed the database
    cmds:
      - rm -f data/comp370.db
      - uv run python scripts/python/seed.py
    silent: true

  test:
    desc: Test the project
    deps:
      - latex:test
      - python:test
    cmds: []
    silent: true

  check:
    desc: Check for linting/formatting errors
    deps:
      - latex:check
      - toml:check
      - yaml:check
      - python:check
    cmds: []
    silent: true

  fix:
    desc: Fix linting/formatting errors
    deps:
      - latex:fix
      - toml:fix
      - yaml:fix
      - python:fix
    cmds: []
    silent: true
