---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  latex: ./tasks/latex.yml
  toml: ./tasks/toml.yml
  yaml: ./tasks/yaml.yml
  python: ./tasks/python.yml
  db: ./tasks/db.yml
  data: ./tasks/data.yml
  annotations: ./tasks/annotations.yml
  statistics: ./tasks/statistics.yml
  docker:
    taskfile: ./tasks/container.yml
    vars:
      RUNTIME: docker
  podman:
    taskfile: ./tasks/container.yml
    vars:
      RUNTIME: podman

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean the project
    silent: true
    deps:
      - latex:clean
    cmds: []

  build:
    desc: Build the project
    silent: true
    deps:
      - latex:build
    cmds: []

  run:
    desc: Run the project
    silent: true
    deps:
      - python:run
    cmds: []

  test:
    desc: Test the project
    silent: true
    deps:
      - latex:test
      - python:test
    cmds: []

  check:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - latex:check
      - toml:check
      - yaml:check
      - python:check
    cmds: []

  fix:
    desc: Fix linting/formatting errors
    silent: true
    deps:
      - latex:fix
      - toml:fix
      - yaml:fix
      - python:fix
    cmds: []
