COMMON_NAMES = {
    "jerry": "Jerry Seinfeld",
    "george": "George Costanza",
    "elaine": "Elaine Benes",
    "kramer": "Cosmo Kramer",
    "newman": "Newman",
    "ruthie": "Ruthie Cohen",
    "morty": "Morty Seinfeld",
    "helen": "Helen Seinfeld",
    "frank": "Frank Costanza",
    "estelle": "Estelle Costanza",
    "leo": "Uncle Leo",
    "babs": "Babs Kramer",
    "david": "David Puddy",
    "puddy": "David Puddy",
    "tim": "Tim Whatley",
    "kenny": "Kenny Bania",
    "lloyd": "Lloyd Braun",
    "jackie": "Jackie Chiles",
    "jacopo": "Jacopo Peterman",
    "justin": "Justin Pitt",
    "robin": "Robin",
    "babu": "Babu Bhatt",
    "soup nazi": "Yev Kassem",
}

TITLES = [
    "mr",
    "mrs",
    "ms",
    "miss",
    "dr",
    "prof",
    "professor",
    "rev",
    "sir",
]

SUFFIXES = [
    "jr",
    "sr",
    "ii",
    "iii",
    "iv",
    "v",
    "esq",
    "phd",
    "md",
    "dds",
]
